### ISSUE TITLE
Unknown Encoding

### ISSUE THREAD

**Issue by fishcharlie** [neet/masto.js#1145]
I keep getting an unknown encoding error.

```
app-1  | MastoUnexpectedError: The server returned data with an unknown encoding. The server may be down.
app-1  |     at HttpNativeImpl.<anonymous> (/project/node_modules/masto/dist/index.cjs:941:27)
app-1  |     at Generator.next (<anonymous>)
app-1  |     at /project/node_modules/masto/dist/index.cjs:78:71
app-1  |     at new Promise (<anonymous>)
app-1  |     at __awaiter (/project/node_modules/masto/dist/index.cjs:74:12)
app-1  |     at HttpNativeImpl.createError (/project/node_modules/masto/dist/index.cjs:937:16)
app-1  |     at HttpNativeImpl.<anonymous> (/project/node_modules/masto/dist/index.cjs:920:34)
app-1  |     at Generator.next (<anonymous>)
app-1  |     at fulfilled (/project/node_modules/masto/dist/index.cjs:75:58)
app-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Here is some very rough example code of what I'm trying to do:

```js
import { createStreamingAPIClient as MastoStream } from "masto";
const masto = MastoStream({
    "accessToken": socialNetwork.credentials.password,
    "streamingApiUrl": `wss://streaming.mastodon.social/api/v1/streaming`
});
convertAsyncIterableToCallback(masto.direct.subscribe().values(), (err, item) => {
    console.log(item);
});

function convertAsyncIterableToCallback(
	asyncIterable,
	callback
): void {
	(async () => {
		try {
			for await (const item of asyncIterable) {
				callback(null, item);
			}
			callback(null, null); // Signal end of iteration
		} catch (err) {
			callback(err instanceof Error ? err : new Error(String(err)), null);
		}
	})();
}
```

Any ideas what could be going wrong here? It really doesn't seem like Mastodon.social is down.

**Comment by fishcharlie** [comment]
It actually looks like this might be caused when sending a private direct message to my Mastodon account using [Ivory](https://tapbots.com/ivory/) when using [Proxyman](https://proxyman.io).

Absolutely no idea why that would be happening tho...

**Comment by neet** [comment]
Hi @fishcharlie, thank you for reporting an issue.

It seems that your `streamingApiUrl` is incorrect. The proper `streamingApiUrl` for the instance https://mastodon.social is `wss://streaming.mastodon.social` which does not contain paths after the hostname. You can obtain the details for the configurations of your instance from `/api/v2/instance`.

If you still have any problem, feel free to write a comment here.

**Comment by neet** [comment]
Closing due to inactivity. Feel free to reopen it if you still have a problem
