### ISSUE TITLE
Build of latest version is broken

### ISSUE THREAD

**Issue by lostfictions** [neet/masto.js#488]
Hi again,

Not sure what's happened, but I'm getting an error with the latest version (4.1.15) of masto.js:

```
<src>/node_modules/masto/dist/index.js:2778
var httpRequest = jest.fn();
                  ^
ReferenceError: jest is not defined
    at Object.<anonymous> (<src>/node_modules/masto/dist/index.js:2778:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/s/Code/wikihow/src/twoot.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

Sure enough, the library is now bundling code using Jest mocks for some reason. Check [dist/index.js](https://unpkg.com/masto@4.1.15/dist/index.js) and search for "jest":

```js
var httpRequest = jest.fn();
var httpGet = jest.fn();
var httpPost = jest.fn();
var httpPatch = jest.fn();
var httpPut = jest.fn();
var httpDelete = jest.fn();
var HttpMockImpl = /** @class */ (function () {
    function HttpMockImpl() {
        this.request = httpRequest;
        this.get = httpGet;
        this.post = httpPost;
        this.patch = httpPatch;
        this.put = httpPut;
        this.delete = httpDelete;
    }
    HttpMockImpl.prototype.clear = function () {
        httpRequest.mockClear();
        httpGet.mockClear();
        httpPost.mockClear();
        httpPatch.mockClear();
        httpPut.mockClear();
        httpDelete.mockClear();
    };
    return HttpMockImpl;
}());
```

**Comment by neet** [comment]
Sorry for lacking tests, this is because I did `export *` from `src/http` which also includes `HttpMock` that is a mock implementation of HTTP request used with Jest. The bug fix will be released soon

**Comment by lostfictions** [comment]
Thanks for the fast response and for the fix!
