### ISSUE TITLE
Using with Akkoma

### ISSUE THREAD

**Issue by Andrmist** [neet/masto.js#666]
Hi, How can I use this package to create an Akkoma bot? Akkoma has Mastodon API which I want to use, but masto.js gives an error due to different versions

```
TypeError: Invalid Version: 2.7.2 (compatible; Akkoma 3.3.0)
    at new SemVer (/home/master/work/fedibots/chadbot/node_modules/.pnpm/semver@7.3.8/node_modules/semver/classes/semver.js:38:13)
    at compare (/home/master/work/fedibots/chadbot/node_modules/.pnpm/semver@7.3.8/node_modules/semver/functions/compare.js:3:3)
    at Object.lt (/home/master/work/fedibots/chadbot/node_modules/.pnpm/semver@7.3.8/node_modules/semver/functions/lt.js:2:29)
    at descriptor.value [as streamUser] (/home/master/work/fedibots/chadbot/node_modules/.pnpm/masto@4.4.1/node_modules/masto/dist/index.js:352:33)
    at main (/home/master/work/fedibots/chadbot/dist/index.js:34:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by neet** [comment]
Hi @Andrmist Thank you for the report

I've never used Akkoma, but it seems your instance has returned `"2.7.2 (compatible; Akkoma 3.3.0)"` as their Mastodon version which is not a valid [semver](https://semver.org/). Masto.js requires servers to provide version information for improving backward compatibility and offering more informative error messages.

I can provide an option to disable the version checking in another PR.

**Comment by neet** [comment]
@Andrmist I published a new beta version that comes with an option to disable version checking. Could you verify the option  suppresses the error? You can try it with:

```
npm install masto@4.5.0-rc1
```

And then

```js
const login = await login({ ..., disableVersionCheck: true });
```

**Comment by Andrmist** [comment]
Thanks, I'll try when I get home

**Comment by Andrmist** [comment]
It works like a charm! Thanks a lot for your work
![result](https://user-images.githubusercontent.com/13292397/200881650-2ca93836-d464-4941-bdf5-472e2cf46c06.png)
