### ISSUE TITLE
"Invalid Version: yay yay"

### ISSUE THREAD

**Issue by s-rd** [neet/masto.js#668]
Hi!

Reaching out as I was trying to set up a bot using this library, using the example in the readme but getting a somewhat strange error:

```bash
TypeError: Invalid Version: yay yay
    at new SemVer (/Users/simon.dagfinrud/Dev/forma/bot/node_modules/semver/classes/semver.js:38:13)
    at compare (/Users/simon.dagfinrud/Dev/forma/bot/node_modules/semver/functions/compare.js:3:3)
    at Object.lt (/Users/simon.dagfinrud/Dev/forma/bot/node_modules/semver/functions/lt.js:2:29)
    at StatusRepository.descriptor.value [as create] (file:///Users/simon.dagfinrud/Dev/forma/bot/node_modules/masto/dist/index.mjs:351:33)
    at main (file:///Users/simon.dagfinrud/Dev/forma/bot/main.js:12:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Using this code:
```js
import { login } from 'masto'
import dotenv from 'dotenv'

dotenv.config()

async function main() {
  const masto = await login({
    url: process.env.SERVER_URL,
    accessToken: process.env.ACCESS_TOKEN,
  })

  await masto.statuses.create({
    status: 'Hello Mastodon!',
    visibility: 'direct',
  })
}

main().catch((error) => {
  console.error(error)
})
```

I did a quick search in the codebase and found it referenced here:

https://github.com/neet/masto.js/blob/fab6efe1c397d3418ebb3a5728608d5ada434eaf/src/entrypoints/nodejs.ts#L11

So basically, I'm just asking if this is intended – if it is, no worries and apologies for spamming with this issue, but I would perhaps consider throwing in some notes about it in the docs :)

Cheers!

--
For good measure: running on node `v16.17.0`.

**Comment by neet** [comment]
Oh, how embarrassing... It was my local test to check if `disableVersionCheck` bypasses version check correctly.

I made a patch in #669  and will soon be released

**Comment by neet** [comment]
ok no more yay yay

**Comment by s-rd** [comment]
@neet So quick!

Haha ok, figured maybe that would be the case 😅 

Thanks 🙏🏻
