### ISSUE TITLE
disableVersionCheck parameter does not work

### ISSUE THREAD

**Issue by catgirlinspace** [neet/masto.js#852]
Passing in the `disableVersionCheck` parameter does not actually disable the version check. 
```ts
async function getMasto() {
  return await login({
	url: "https://fediverse.catgirlin.space",
	accessToken: process.env.FEDIVERSE_ACCESS_TOKEN,
	disableVersionCheck: true,
  });
}
```
Traceback
```
/Users/catgirl/Projects/splatnet3-exporter/node_modules/semver/classes/semver.js:38
      throw new TypeError(`Invalid Version: ${version}`)
            ^

TypeError: Invalid Version: 2.7.2 (compatible; Akkoma 3.5.0-14-gd9508474)
    at new SemVer (/Users/catgirl/Projects/splatnet3-exporter/node_modules/semver/classes/semver.js:38:13)
    at buildHttpContext (file:///Users/catgirl/Projects/splatnet3-exporter/node_modules/masto/dist/index.js:3820:63)
    at createClient (file:///Users/catgirl/Projects/splatnet3-exporter/node_modules/masto/dist/index.js:3837:50)
    at file:///Users/catgirl/Projects/splatnet3-exporter/node_modules/masto/dist/index.js:3849:12
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/catgirl/Projects/splatnet3-exporter/node_modules/masto/dist/index.js:515:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by catgirlinspace** [comment]
thanks for the quick fix!!
